package org.example.loficonnect.subscription.model.enums;

public enum AuditEventType {
    CHECKOUT_STARTED,
    CHECKOUT_EXPIRED,
    CHECKOUT_REMINDER_SENT,
    PADDLE_WEBHOOK_RECEIVED,
    WEBHOOK_VERIFICATION_FAILED,
    DUPLICATE_WEBHOOK_IGNORED,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_STATUS_CHANGED,
    PLAN_CHANGED,
    ACCESS_GRANTED,
    ACCESS_REVOKED,
    API_KEY_GENERATED,
    API_KEY_REVOKED,
    BUNDLED_PROVISIONING_STARTED,
    BUNDLED_PROVISIONING_COMPLETED,
    ADMIN_CHANGED_SUBSCRIPTION,
    CANCELLATION_REQUESTED,
    GRACE_PERIOD_STARTED,
    READ_ONLY_STARTED,
    SUBSCRIPTION_SUSPENDED,
    REFUND_REQUESTED,
    REFUND_APPROVED,
    REFUND_REJECTED,
    SYNC_ERROR
}
