version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: root00023/lofi-connect:7.2.0  # Specify your custom image tag here
    container_name: lofi-connect-container
    ports:
      - "8080:8080"