version: "3.8"

services:
  database:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: lofi_connect_database_1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

  app:
    build: .
    container_name: spring_backend
    image: root00023/lofi-connect:3.0.0
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/lofi_connect_database_1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    networks:
      - spring-net

volumes:
  postgres_data:

networks:
  spring-net: