gohighlevel:
  client-id: 689b932c1e999f049e317c33-me8xkopq
  client-secret: 85aa301a-2002-455f-a477-5cffe54dedd7
  redirect-uri: https://loficonnect.lofistack.com/api/v1/authorization/redirect
  base-url: https://marketplace.gohighlevel.com
  code-url: oauth/chooselocation
  token-url: https://services.leadconnectorhq.com/oauth/token
  scopes:
    - contacts.readonly
    - contacts.write
    - forms.readonly
    - forms.write
    - calendars.write
    - calendars.readonly
    - calendars/events.readonly
    - calendars/events.write
    - users.readonly
    - users.write
    - links.write
    - links.readonly
    - oauth.write
    - oauth.readonly
    - businesses.write
    - businesses.readonly
    - calendars/groups.readonly
    - calendars/groups.write
    - calendars/resources.readonly
    - calendars/resources.write
    - campaigns.readonly
    #    - companies.readonly
    - objects/schema.readonly
    - objects/schema.write
    - objects/record.write
    - objects/record.readonly
    - associations.readonly
    - associations.write
    - associations/relation.write
    - associations/relation.readonly
    - locations/customFields.readonly
    - locations/customFields.write
    - conversations.readonly
    - conversations.write
    - conversations/message.readonly
    - conversations/message.write
    - conversations/livechat.write
    - conversations/reports.readonly
    - emails/schedule.readonly
    - emails/builder.write
    - emails/builder.readonly
    - invoices.readonly
    - invoices.write
    - invoices/template.write
    - invoices/template.readonly
    - invoices/schedule.write
    - invoices/schedule.readonly
    - invoices/estimate.write
    - invoices/estimate.readonly
    - locations/customValues.readonly
    - locations/customValues.write
    - locations/templates.readonly
    - locations.readonly
    #    - locations.internal-access-only
    - locations/tags.readonly
    - locations/tags.write
    - locations/tasks.readonly
    - locations/tasks.write
    - medias.readonly
    - medias.write
    - marketplace-installer-details.readonly
    - charges.write
    - charges.readonly
    - blogs/check-slug.readonly
    - blogs/post-update.write
    - blogs/post.write
    - blogs/posts.readonly
    - blogs/author.readonly
    - blogs/category.readonly
    - blogs/list.readonly
    - funnels/redirect.write
    - funnels/redirect.readonly
    - funnels/page.readonly
    - funnels/funnel.readonly
    - funnels/pagecount.readonly
    - opportunities.readonly
    - opportunities.write
    - payments/integration.write
    - payments/integration.readonly
    - payments/orders.readonly
    - payments/orders.collectPayment
    - payments/orders.write
    - payments/transactions.readonly
    - payments/subscriptions.readonly
    - payments/coupons.readonly
    - payments/coupons.write
    - payments/custom-provider.write
    - payments/custom-provider.readonly
    - products.readonly
    - products/prices.readonly
    - products/prices.write
    - products.write
    - products/collection.readonly
    - products/collection.write
    - socialplanner/oauth.readonly
    - socialplanner/oauth.write
    - socialplanner/post.readonly
    - socialplanner/post.write
    - socialplanner/account.readonly
    - socialplanner/account.write
    - socialplanner/csv.write
    - socialplanner/csv.readonly
    - socialplanner/category.readonly
    - socialplanner/category.write
    - socialplanner/tag.readonly
    - socialplanner/tag.write
    - surveys.readonly
    - workflows.readonly
    - courses.write
    - courses.readonly
    - lc-email.readonly
    - recurring-tasks.readonly
    - recurring-tasks.write
    - saas/location.read
    - saas/location.write
    - store/shipping.write
    - store/setting.readonly
    - store/setting.write
    - wordpress.site.readonly
    - twilioaccount.read
    - phonenumbers.read
    - numberpools.read
    - documents_contracts/list.readonly
    - documents_contracts/sendLink.write
    - documents_contracts_template/sendLink.write
    - documents_contracts_template/list.readonly
    - voice-ai-dashboard.readonly
    - voice-ai-agents.readonly
    - voice-ai-agents.write
    - voice-ai-agent-goals.readonly
    - voice-ai-agent-goals.write
    - knowledge-bases.readonly
    - knowledge-bases.write
    - conversation-ai.readonly
    - conversation-ai.write

spring:
  datasource:
    url: jdbc:postgresql://lofi-connect-rds.cyj6ccy6uyug.us-east-1.rds.amazonaws.com:5432/lofi_connect_database_1
    username: postgres
    password: vG4mXp9Jq2LsTzAK4
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # use validate / update / create / create-drop as per need
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    time-zone: UTC

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  forward-headers-strategy: framework
