# -----------------------
# PostgreSQL configuration
# -----------------------
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=lofi_connect_database_1
POSTGRES_USER=postgres
POSTGRES_PASSWORD=1234
# -----------------------
# JWT configuration
# -----------------------
JWT_SECRET=X9bP7kQ4vM1rT6sJ2wL8fC0hD5nV3yZ7
JWT_EXPIRATION=3600000

FRONT_END_URL=http://localhost:3000/portal/connections?app-key=

GHL_CLIENT_ID=689b932c1e999f049e317c33-me8xkopq
GHL_CLIENT_SECRET=85aa301a-2002-455f-a477-5cffe54dedd7
GHL_BASE_URL=https://marketplace.gohighlevel.com/
GHL_CODE_URL=oauth/chooselocation
GHL_REDIRECT_URI=http://localhost:8080/api/v1/authorization/redirect
GHL_TOKEN_URL=https://services.leadconnectorhq.com/oauth/token

# ----------------------
# GMAIL Configuration
# ----------------------
MAIL_USERNAME=robiulhassan.dev07@gmail.com
MAIL_PASSWORD=nuto fnru oyys xwhj
SENDER_NAME=LofiConnect Security Team
# Otp and reset token configuration
OTP_EXPIRY_DURATION_MINUTES=5
reset.token.expiry.minutes=5