###
POST http://localhost:8080/api/v1/ghl/calendars/events/appointments
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "title": "Test Event 3",
  "meeting_location_type": "custom",
  "meeting_location_id": "custom_0",
  "override_location_config": true,
  "appointment_status": "confirmed",
  "assigned_user_id": "zlOSBQcKz3njTjHUdsUZ",
  "address": "Zoom",
  "ignore_date_range": true,
  "to_notify": true,
  "ignore_free_slot_validation": true,
  "rrule": "RRULE:FREQ=DAILY;INTERVAL=1;COUNT=5",
  "calendar_id": "2mqNXde5z5IYQjNKcprY",
  "location_id": "IxfSlEIQQeiOYQlVEApa",
  "contact_id": "Lq95Y9oQzB4KojmsjUxs",
  "start_time": "2026-06-23T03:30:00+05:30",
  "end_time": "2027-06-23T04:30:00+05:30"
}


###
POST http://localhost:8080/api/v1/ghl/calendars/events/block-slots
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "title": "Test Event 4",
  "calendar_id": "AZh6xFlrxoNQ1wQ9J4c9",
  "assigned_user_id": "",
  "location_id": "IxfSlEIQQeiOYQlVEApa",
  "time_zone": "Pacific/Apia",
  "start_date": "2025-11-03",
  "start_time": "10:00:00",
  "end_date": "2025-11-03",
  "end_time": "10:00:00"
}

###
GET http://localhost:8080/api/v1/ghl/calendars/events/appointments/wFPdS5BfKAYBFW8MR3pg
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

###
GET http://localhost:8080/api/v1/ghl/calendars/events/events
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0


###
GET http://localhost:8080/api/v1/ghl/calendars/events/blocked-slots
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

###
PUT http://localhost:8080/api/v1/ghl/calendars/events/appointments/AZh6xFlrxoNQ1wQ9J4c9
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "title": "Updated Test Event",
  "meeting_location_type": "custom",
  "meeting_location_id": "custom_0",
  "override_location_config": true,
  "appointment_status": "confirmed",
  "assigned_user_id": "zlOSBQcKz3njTjHUdsUZ",
  "address": "Bangladesh",
  "ignore_date_range": true,
  "to_notify": true,
  "ignore_free_slot_validation": true,
  "rrule": "RRULE:FREQ=DAILY;INTERVAL=1;COUNT=5",
  "calendar_id": "2mqNXde5z5IYQjNKcprY",
  "start_time": "2027-06-23T03:30:00+05:30",
  "end_time": "2027-06-23T04:30:00+05:30"
}

###
PUT http://localhost:8080/api/v1/ghl/calendars/events/block-slots/AZh6xFlrxoNQ1wQ9J4c9
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "title": "Block Test",
  "calendar_id": "2mqNXde5z5IYQjNKcprY",
  "assigned_user_id": "",
  "location_id": "IxfSlEIQQeiOYQlVEApa",
  "time_zone": "Pacific/Apia",
  "start_date": "2025-11-03",
  "start_time": "10:00:00",
  "end_date": "2025-11-03",
  "end_time": "10:00:00"
}

###
DELETE http://localhost:8080/api/v1/ghl/calendars/events/events/AZh6xFlrxoNQ1wQ9J4c9
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0