###
POST http://localhost:8080/api/v1/ghl/calendars/events/appointments
Content-Type: application/json
Authorization: Bearer Bn0IiD8IIk2xazO6007WxJbDuVapqH4Fi2ZhrSyrnFs

{
  "title": "Test Event",
  "meeting_location_type": "custom",
  "meeting_location_id": "custom_0",
  "override_location_config": true,
  "appointment_status": "confirmed",
  "assigned_user_id": "zlOSBQcKz3njTjHUdsUZ",
  "description": "This is a test Event",
  "address": "Zoom",
  "ignore_date_range": true,
  "to_notify": true,
  "ignore_free_slot_validation": true,
  "rrule": "RRULE:FREQ=DAILY;INTERVAL=1;COUNT=5",
  "calendar_id": "2mqNXde5z5IYQjNKcprY",
  "contact_id": "Lq95Y9oQzB4KojmsjUxs",
  "time_zone": "Pacific/Apia",
  "start_date": "2025-11-04",
  "start_time": "10:00:00",
  "end_date": "2025-11-06",
  "end_time": "10:00:00"
}

###
POST http://localhost:8080/api/v1/ghl/calendars/events/block-slots
Content-Type: application/json
Authorization: Bearer Bn0IiD8IIk2xazO6007WxJbDuVapqH4Fi2ZhrSyrnFs

{
  "title": "Test Event 2",
  "calendar_id": "2mqNXde5z5IYQjNKcprY",
  "assigned_user_id": "zlOSBQcKz3njTjHUdsUZ",
  "location_id": "IxfSlEIQQeiOYQlVEApa",
  "time_zone": "Pacific/Apia",
  "start_date": "2025-11-04",
  "start_time": "10:00:00",
  "end_date": "2025-11-04",
  "end_time": "10:00:00"
}

###
GET http://localhost:8080/api/v1/ghl/calendars/events/appointments/V6HRVMCwpAHoJfz4Wb0n
Content-Type: application/json
Authorization: Bearer Bn0IiD8IIk2xazO6007WxJbDuVapqH4Fi2ZhrSyrnFs


###
GET http://localhost:8080/api/v1/ghl/calendars/events/events?calendar-id=2mqNXde5z5IYQjNKcprY&time-zone=America%2FNew_York&start-date=2021-11-01&start-time=10%3A00%3A00&end-date=2026-11-01&end-time=10%3A00%3A00&location-id=IxfSlEIQQeiOYQlVEApa
Content-Type: application/json
Authorization: Bearer Bn0IiD8IIk2xazO6007WxJbDuVapqH4Fi2ZhrSyrnFs


###
GET http://localhost:8080/api/v1/ghl/calendars/events/blocked-slots?calendar-id=2mqNXde5z5IYQjNKcprY&time-zone=America%2FNew_York&start-date=2021-05-11&start-time=10%3A00%3A00&end-date=2026-05-12&end-time=10%3A00%3A00&location-id=IxfSlEIQQeiOYQlVEApa
Content-Type: application/json
Authorization: Bearer Bn0IiD8IIk2xazO6007WxJbDuVapqH4Fi2ZhrSyrnFs

###
PUT http://localhost:8080/api/v1/ghl/calendars/events/appointments/V6HRVMCwpAHoJfz4Wb0n
Content-Type: application/json
Authorization: Bearer Bn0IiD8IIk2xazO6007WxJbDuVapqH4Fi2ZhrSyrnFs

{
  "title": "Updated Test Event",
  "meeting_location_type": "custom",
  "meeting_location_id": "custom_0",
  "override_location_config": true,
  "appointment_status": "confirmed",
  "assigned_user_id": "zlOSBQcKz3njTjHUdsUZ",
  "address": "Bangladesh",
  "ignore_date_range": true,
  "to_notify": true,
  "ignore_free_slot_validation": true,
  "rrule": "RRULE:FREQ=DAILY;INTERVAL=1;COUNT=5",
  "calendar_id": "2mqNXde5z5IYQjNKcprY",
  "time_zone": "Pacific/Apia",
  "start_date": "2025-11-04",
  "start_time": "10:00:00",
  "end_date": "2025-11-04",
  "end_time": "10:00:00"
}

###
PUT http://localhost:8080/api/v1/ghl/calendars/events/block-slots/V6HRVMCwpAHoJfz4Wb0n
Content-Type: application/json
Authorization: Bearer Bn0IiD8IIk2xazO6007WxJbDuVapqH4Fi2ZhrSyrnFs

{
  "title": "Block Test",
  "calendar_id": "2mqNXde5z5IYQjNKcprY",
  "assigned_user_id": "",
  "location_id": "IxfSlEIQQeiOYQlVEApa",
  "time_zone": "Pacific/Apia",
  "start_date": "2025-11-03",
  "start_time": "10:00:00",
  "end_date": "2025-11-03",
  "end_time": "10:00:00"
}

###
DELETE http://localhost:8080/api/v1/ghl/calendars/events/events/V6HRVMCwpAHoJfz4Wb0n
Content-Type: application/json
Authorization: Bearer Bn0IiD8IIk2xazO6007WxJbDuVapqH4Fi2ZhrSyrnFs