###
POST http://localhost:8080/api/v1/ghl/contacts
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "first_name": "Test First Name 1",
  "last_name": "Test Last Name 1",
  "name": "Test Name 1",
  "email": "testemail1@email.com",
  "gender": "string",
  "phone": "string",
  "address1": "string",
  "city": "string",
  "state": "string",
  "postal_code": "string",
  "website": "string",
  "timezone": "string",
  "dnd": true,
  "tags": [
    "string"
  ],
  "custom_fields": [
    {
      "custom_field_id": "string",
      "custom_field_key": "string",
      "custom_field_value": "string"
    }
  ],
  "source": "string",
  "country": "string",
  "company_name": "string"
}

###
GET http://localhost:8080/api/v1/ghl/contacts/{{contact-id}}
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

###
PUT http://localhost:8080/api/v1/ghl/contacts/{{contact-id}}
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "first_name": "string",
  "last_name": "string",
  "name": "string",
  "email": "string",
  "phone": "string",
  "address1": "string",
  "city": "string",
  "state": "string",
  "postal_code": "string",
  "website": "string",
  "timezone": "string",
  "dnd": true,
  "inbound_dnd_settings": {
    "all": {
      "status": "string",
      "message": "string"
    }
  },
  "tags": [
    "string"
  ],
  "custom_fields": [
    {
      "id": "string",
      "key": "string",
      "field_value": "string"
    }
  ],
  "source": "string",
  "country": "string",
  "assigned_to": "string"
}

###
DELETE http://localhost:8080/api/v1/ghl/contacts/{{contact-id}}
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

###
GET http://localhost:8080/api/v1/ghl/contacts/business/{{business-id}}
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

###
POST http://localhost:8080/api/v1/ghl/contacts/upsert
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "first_name": "string",
  "last_name": "string",
  "name": "string",
  "email": "string",
  "gender": "string",
  "phone": "string",
  "address1": "string",
  "city": "string",
  "state": "string",
  "postal_code": "string",
  "website": "string",
  "timezone": "string",
  "dnd": true,
  "inbound_dnd_settings": {
    "all": {
      "status": "string",
      "message": "string"
    }
  },
  "tags": [
    "string"
  ],
  "custom_fields": [
    {
      "id": "string",
      "key": "string",
      "field_value": "string"
    }
  ],
  "source": "string",
  "country": "string",
  "company_name": "string",
  "assigned_to": "string"
}