###
POST http://localhost:8080/api/v1/ghl/custom-fields
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "name": "Custom Field",
  "data_type": "TEXT",
  "placeholder": "Placeholder Text",
  "accepted_format": [
    ".pdf"
  ],
  "is_multiple_file": true,
  "max_number_of_files": 0,
  "text_box_list_options": [
    {
      "label": "First",
      "prefill_value": "ls"
    }
  ],
  "position": 0,
  "model": "opportunity"
}


###
POST http://localhost:8080/api/v1/ghl/custom-fields/files?custom-field-id=12&maxFiles=1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "file": "file.pdf"
}


###
GET http://localhost:8080/api/v1/ghl/custom-fields
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0


###
GET http://localhost:8080/api/v1/ghl/custom-fields/gDntHf5ZLyuEFAoAXJ6x
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0


###
PUT http://localhost:8080/api/v1/ghl/custom-fields/gDntHf5ZLyuEFAoAXJ6x
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "name": "Custom Field 2",
  "placeholder": "Placeholder Text 2",
  "accepted_format": [
    ".docx"
  ],
  "is_multiple_file": true,
  "max_number_of_files": 3,
  "text_box_list_options": [
    {
      "label": "First",
      "prefill_value": "ls"
    }
  ],
  "position": 0,
  "model": "opportunity"
}


###
DELETE http://localhost:8080/api/v1/ghl/custom-fields/gDntHf5ZLyuEFAoAXJ6x
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0
