### Create Custom Field
### Full Payload
POST http://localhost:8080/api/v1/ghl/custom-fields
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Custom Field 2",
  "data_type": "TEXT",
  "placeholder": "Placeholder Text",
  "accepted_format": [
    ".pdf"
  ],
  "is_multiple_file": true,
  "max_number_of_files": 0,
  "text_box_list_options": [
    {
      "label": "First",
      "prefill_value": "ls"
    }
  ],
  "position": 0,
  "model": "opportunity"
}


### Only Required Fields
POST http://localhost:8080/api/v1/ghl/custom-fields
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Custom Field 3",
  "data_type": "TEXT"
}

### Uploads File to customFields
### Full Payload
POST http://localhost:8080/api/v1/ghl/custom-fields/files?custom-field-id=12&maxFiles=1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{bearerToken}}

{
  "file": "image/jpeg"
}


### Required Part
POST http://localhost:8080/api/v1/ghl/custom-fields/files
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{bearerToken}}


###
GET http://localhost:8080/api/v1/ghl/custom-fields
Content-Type: application/json
Authorization: Bearer {{bearerToken}}


###
GET http://localhost:8080/api/v1/ghl/custom-fields/1BC04Z7i9BPqltv833V6
Authorization: Bearer {{bearerToken}}


### Update Custom Field
### Full Payload
PUT http://localhost:8080/api/v1/ghl/custom-fields/1BC04Z7i9BPqltv833V6
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Custom Field 2",
  "placeholder": "Placeholder Text 2",
  "accepted_format": [
    ".docx"
  ],
  "is_multiple_file": true,
  "max_number_of_files": 3,
  "text_box_list_options": [
    {
      "label": "First",
      "prefill_value": "ls"
    }
  ],
  "position": 0,
  "model": "contact"
}


### Only Required Fields
PUT http://localhost:8080/api/v1/ghl/custom-fields/1BC04Z7i9BPqltv833V6
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Custom Field 0"
}

###
DELETE http://localhost:8080/api/v1/ghl/custom-fields/chjZrhx0PNbUreHkTBs7
Authorization: Bearer {{bearerToken}}
