###
POST http://localhost:8080/api/v1/ghl/custom-values
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "name": "Test Custom Value",
  "value": "Test value"
}

###
GET http://localhost:8080/api/v1/ghl/custom-values
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

###
GET http://localhost:8080/api/v1/ghl/locations/custom-values/LJ9zr1Cdcy7NXAVklgo9
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

###
PUT http://localhost:8080/api/v1/ghl/custom-values/LJ9zr1Cdcy7NXAVklgo9
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "name": "Updated Custom Value",
  "value": "Custom value updated"
}

###
DELETE http://localhost:8080/api/v1/ghl/custom-values/LJ9zr1Cdcy7NXAVklgo9
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0
