###Create Opportunity
### Full Payload
POST http://localhost:8080/api/v1/ghl/opportunities
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "pipeline_id": "HceOPjAqAcIBkA4Nsfev",
  "name": "Test Opportunity 2",
  "pipeline_stage_id": "a4aa56f5-b332-44ca-9329-c860afc3908b",
  "status": "open",
  "contact_id": "Lq95Y9oQzB4KojmsjUxs",
  "monetary_value": 0,
  "assigned_to": "i1CcsDXpngqsHTZXkEfJ",
  "custom_fields": [
    {
      "id": "EHnICTrpVnzdTdk6pWx7",
      "key": "contact.dhiman__drop_down",
      "field_value": "Dhiman | Drop Down"
    }
  ]
}


### Only Required Fields
POST http://localhost:8080/api/v1/ghl/opportunities
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "pipeline_id": "HceOPjAqAcIBkA4Nsfev",
  "name": "Test Opportunity RF",
  "pipeline_stage_id": "a4aa56f5-b332-44ca-9329-c860afc3908b",
  "status": "open",
  "contact_id": "Lq95Y9oQzB4KojmsjUxs"
}

### Upsert Contact
### Full Pyload
POST http://localhost:8080/api/v1/ghl/opportunities/upsert
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "pipeline_id": "HceOPjAqAcIBkA4Nsfev",
  "contact_id": "Lq95Y9oQzB4KojmsjUxs",
  "name": "First Opps",
  "status": "open",
  "pipeline_stage_id": "a4aa56f5-b332-44ca-9329-c860afc3908b",
  "monetary_value": 0,
  "assigned_to": "i1CcsDXpngqsHTZXkEfJ"
}


### Only Required Fields
POST http://localhost:8080/api/v1/ghl/opportunities/upsert
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "pipeline_id": "HceOPjAqAcIBkA4Nsfev",
  "contact_id": "Lq95Y9oQzB4KojmsjUxs"
}

###
GET http://localhost:8080/api/v1/ghl/opportunities/Q30XxSWLbUpDKjZRfmSM
Content-Type: application/json
Authorization: Bearer {{bearerToken}}


### Update Opportunity
### Full Payload
PUT http://localhost:8080/api/v1/ghl/opportunities/Q30XxSWLbUpDKjZRfmSM
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "pipeline_id": "HceOPjAqAcIBkA4Nsfev",
  "name": "First Opps 2",
  "pipeline_stage_id": "a4aa56f5-b332-44ca-9329-c860afc3908b",
  "status": "open",
  "monetary_value": 0,
  "assigned_to": "i1CcsDXpngqsHTZXkEfJ",
  "custom_fields": [
    {
      "id": "EHnICTrpVnzdTdk6pWx7",
      "key": "contact.dhiman__drop_down",
      "field_value": "Dhiman | Drop Down"
    }
  ]
}


### Only Required Fields
PUT http://localhost:8080/api/v1/ghl/opportunities/Q30XxSWLbUpDKjZRfmSM
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{

}

### Update Opportunity Status
### Full Payload
PUT http://localhost:8080/api/v1/ghl/opportunities/Q30XxSWLbUpDKjZRfmSM/status
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "status": "open"
}


###
DELETE http://localhost:8080/api/v1/ghl/opportunities/Q30XxSWLbUpDKjZRfmSM
Content-Type: application/json
Authorization: Bearer {{bearerToken}}
