###
POST http://localhost:8080/api/v1/ghl/contacts/search
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "phone": "",
  "email": "test1@gmail.com",
  "page_limit": 10,
  "page": 1
}


###
POST http://localhost:8080/api/v1/ghl/locations/tasks/search
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "contact_id": [
    "Lq95Y9oQzB4KojmsjUxs"
  ],
  "completed": true,
  "assigned_to": [
    "Zs21L9iF4nJUTEVPvo90"
  ],
  "query": "",
  "limit": 10,
  "skip": 0,
  "business_id": ""
}


###
GET http://localhost:8080/api/v1/ghl/contacts/search/duplicate
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/api/v1/ghl/locations/search
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/api/v1/ghl/conversations/search?location-id=IxfSlEIQQeiOYQlVEApa
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/api/v1/ghl/opportunities/search
Authorization: Bearer {{bearerToken}}
