### Create Sub-Account
### Full Payload
POST http://localhost:8080/api/v1/ghl/locations
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Mark Shoes",
  "phone": "+1410039940",
  "company_id": "2Y6wzd96Wjmrl1yEm99j",
  "address": "4th fleet street",
  "city": "New York",
  "state": "Illinois",
  "country": "US",
  "postal_code": "567654",
  "website": "https://google.com",
  "timezone": "Pacific/Apia",
  "prospect_info": {
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@mail.com"
  },
  "settings": {
    "allow_duplicate_contact": true,
    "allow_duplicate_opportunity": true,
    "allow_facebook_name_merge": true,
    "disable_contact_timezone": true
  },
  "social": {
    "facebook_url": "https://www.facebook.com/",
    "google_plus": "https://www.googleplus.com/",
    "linked_in": "https://www.linkedIn.com/",
    "foursquare": "https://www.foursquare.com/",
    "twitter": "https://www.foutwitterrsquare.com/",
    "yelp": "https://www.yelp.com/",
    "instagram": "https://www.instagram.com/",
    "youtube": "https://www.youtube.com/",
    "pinterest": "https://www.pinterest.com/",
    "blog_rss": "https://www.blogRss.com/",
    "google_places_id": "ChIJJGPdVbQTrjsRGUkefteUeFk"
  },
  "twilio": {
    "sid": "AC_XXXXXXXXXXX",
    "auth_token": "77_XXXXXXXXXXX"
  },
  "mailgun": {
    "api_key": "AC_XXXXXXXXXXX",
    "domain": "77_XXXXXXXXXXX"
  },
  "snapshot_id": "XXXXXXXXXXX"
}


### Only Required Fields
POST http://localhost:8080/api/v1/ghl/locations
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Mark Shoes",
  "company_id": "2Y6wzd96Wjmrl1yEm99j"
}


### Additional Required Fields
POST http://localhost:8080/api/v1/ghl/locations
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Mark Shoes",
  "company_id": "2Y6wzd96Wjmrl1yEm99j",
  "prospect_info": {
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@mail.com"
  },
  "twilio": {
    "sid": "AC_XXXXXXXXXXX",
    "auth_token": "77_XXXXXXXXXXX"
  },
  "mailgun": {
    "api_key": "AC_XXXXXXXXXXX",
    "domain": "77_XXXXXXXXXXX"
  }
}

###
GET http://localhost:8080/api/v1/ghl/locations/IxfSlEIQQeiOYQlVEApa
Authorization: Bearer {{bearerToken}}


### Update Sub-Account
### Full Payload
PUT http://localhost:8080/api/v1/ghl/locations/IxfSlEIQQeiOYQlVEApa
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Mark Shoes",
  "phone": "+1410039940",
  "company_id": "2Y6wzd96Wjmrl1yEm99j",
  "address": "4th fleet street",
  "city": "New York",
  "state": "Illinois",
  "country": "US",
  "postal_code": "567654",
  "website": "https://google.com",
  "timezone": "Pacific/Apia",
  "prospect_info": {
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@mail.com"
  },
  "settings": {
    "allow_duplicate_contact": true,
    "allow_duplicate_opportunity": true,
    "allow_facebook_name_merge": true,
    "disable_contact_timezone": true
  },
  "social": {
    "facebook_url": "https://www.facebook.com/",
    "google_plus": "https://www.googleplus.com/",
    "linked_in": "https://www.linkedIn.com/",
    "foursquare": "https://www.foursquare.com/",
    "twitter": "https://www.foutwitterrsquare.com/",
    "yelp": "https://www.yelp.com/",
    "instagram": "https://www.instagram.com/",
    "youtube": "https://www.youtube.com/",
    "pinterest": "https://www.pinterest.com/",
    "blog_rss": "https://www.blogRss.com/",
    "google_places_id": "ChIJJGPdVbQTrjsRGUkefteUeFk"
  },
  "twilio": {
    "sid": "AC_XXXXXXXXXXX",
    "auth_token": "77_XXXXXXXXXXX"
  },
  "mailgun": {
    "api_key": "AC_XXXXXXXXXXX",
    "domain": "77_XXXXXXXXXXX"
  },
  "snapshot": {
    "id": "XXXXXXXXXXX",
    "override": true
  }
}


### Only Required Fields
PUT http://localhost:8080/api/v1/ghl/locations/IxfSlEIQQeiOYQlVEApa
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "company_id": "2Y6wzd96Wjmrl1yEm99j"
}


### Additional Required Fields
PUT http://localhost:8080/api/v1/ghl/locations/IxfSlEIQQeiOYQlVEApa
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "company_id": "2Y6wzd96Wjmrl1yEm99j",
  "prospect_info": {
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@mail.com"
  },
  "twilio": {
    "sid": "AC_XXXXXXXXXXX",
    "auth_token": "77_XXXXXXXXXXX"
  },
  "mailgun": {
    "api_key": "AC_XXXXXXXXXXX",
    "domain": "77_XXXXXXXXXXX"
  },
  "snapshot": {
    "id": "XXXXXXXXXXX"
  }
}

###
DELETE http://localhost:8080/api/v1/ghl/locations/IxfSlEIQQeiOYQlVEApa
Authorization: Bearer {{bearerToken}}
