### Add Tags
### Full Payload
POST http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tags
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "tags": [
    "minim"
  ]
}

###
POST http://localhost:8080/api/v1/ghl/tags?location-id=IxfSlEIQQeiOYQlVEApa
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "new Test Tag 2"
}

###
GET http://localhost:8080/api/v1/ghl/locations/tags
Authorization: Bearer {{bearerToken}}


###
GET http://localhost:8080/api/v1/ghl/tags/67RKz3tBrH2ggtRCwTc3
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

###
PUT http://localhost:8080/api/v1/ghl/locations/tags/67RKz3tBrH2ggtRCwTc3
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Updated New Test Tag"
}

###
DELETE http://localhost:8080/api/v1/ghl/locations/tags/67RKz3tBrH2ggtRCwTc3
Content-Type: application/json
Authorization: Bearer {{bearerToken}}


###
DELETE http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tags
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "tags": [
    "minim"
  ]
}
