###
POST http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tags
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "tags": [
    "minim"
  ]
}

###
POST http://localhost:8080/api/v1/ghl/tags?location-id=IxfSlEIQQeiOYQlVEApa
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "name": "test tag"
}

###
GET http://localhost:8080/api/v1/ghl/locations/tags
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0


###
GET http://localhost:8080/api/v1/ghl/tags/ipkYR856lXDKGqL6UHc7
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

###
PUT http://localhost:8080/api/v1/ghl/locations/tags/ipkYR856lXDKGqL6UHc7
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "name": "consequeat"
}

###
DELETE http://localhost:8080/api/v1/ghl/locations/tags/ipkYR856lXDKGqL6UHc7
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0


###
DELETE http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tags
Content-Type: application/json
Authorization: Bearer cTww1ZoT7gzRK-FENMF3X1ek72zuSu4pRB488OKhoY0

{
  "tags": [
    "minim"
  ]
}
