### Create Task
### Full Payload
POST http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tasks
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "title": "Test task 2",
  "body": "test task",
  "due_date": "2025-10-31",
  "due_time": "10:00:00",
  "time_zone": "Pacific/Apia",
  "completed": true,
  "assigned_to": "i1CcsDXpngqsHTZXkEfJ"
}


### Only Required Fields
POST http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tasks
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "title": "Test task 3",
  "body": "test task",
  "due_date": "2025-10-31",
  "due_time": "10:00:00",
  "time_zone": "Pacific/Apia",
  "completed": true
}


###
GET http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tasks
Content-Type: application/json
Authorization: Bearer {{bearerToken}}


###
GET http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tasks/Sd0tFobtCPbDlXYvgx46
Content-Type: application/json
Authorization: Bearer {{bearerToken}}


### Update Task
### Full Payload
PUT http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tasks/Sd0tFobtCPbDlXYvgx46
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "title": "Updated Task",
  "body": "task updated",
  "due_date": "2025-10-31",
  "due_time": "10:00:00",
  "time_zone": "Pacific/Apia",
  "completed": true,
  "assigned_to": "i1CcsDXpngqsHTZXkEfJ"
}


### Only Required Fields
PUT http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tasks/Sd0tFobtCPbDlXYvgx46
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{

}

### Update Task Completed
### Full Payload
PUT http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tasks/Sd0tFobtCPbDlXYvgx46/completed
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "completed": false
}

###
DELETE http://localhost:8080/api/v1/ghl/contacts/Lq95Y9oQzB4KojmsjUxs/tasks/GDT8arcOAUXhNUDKNfft
Content-Type: application/json
Authorization: Bearer {{bearerToken}}
